# user = User.create!(name: "Meg Howe", email: "meg@example.com", favorite_thing: "Salmon Feeling")
# user = User.create!(name: "Casey Gotcher", email: "casey@example.com", favorite_thing: "travel")
# user = User.create!(name: "Eve Fibonacci", email: "spookyaction@example.com", favorite_thing: "blood")

experience = Experience.create!(title: "Study in Germany", subtasks: "...", notes: "...", user_id: 2, image: "https://www.studying-in-germany.org/wp-content/uploads/2018/07/German-Culture-and-Traditions.jpg")
experience = Experience.create!(title: "Visit the Grand Canyon", subtasks: "...", notes: "...", user_id: 1, image: "https://www.smartertravel.com/wp-content/uploads/2017/08/grand-canyon-sunset-1200x627.jpg")
experience = Experience.create!(title: "Buy a house", subtasks: "...", notes: "...", user_id: 1, image: "https://www.thoughtco.com/thmb/4_TQmRcISDMx8yN6ehd5cSrNCH4=/3500x3500/smart/filters:no_upscale()/capecod-95494553-56a02e403df78cafdaa06dbe.jpg")
experience = Experience.create!(title: "Get a hamster", subtasks: "...", notes: "...", user_id: 3, image: "https://www.thesprucepets.com/thmb/LPnj-N-AcGdZRvf7E6y_Hsf2vqo=/4089x2300/smart/filters:no_upscale()/close-up-of-a-hamster-eating-groundnut-635096689-5c525f88c9e77c0001d7c1fa.jpg")
experience = Experience.create!(title: "Donate Blood", subtasks: "...", notes: "...", user_id: 3, image: "https://consumer.healthday.com/media-library/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yMzYzNDI3Ny9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY3MzQ2Nzk0Mn0.L7XttZzouRiyDO_JdrESxpcUafYOQFpoLrJ6b1X79uw/image.jpg?width=1245&quality=85&coordinates=0%2C74%2C0%2C74&height=700")
# experience = Experience.create!(title: "Write a perform a show in a major city", subtasks: "...", notes: "...")
# experience = Experience.create!(title: "Work on an avocado farm", subtasks: "...", notes: "...")
# experience = Experience.create!(title: "Pick grapes for a living", subtasks: "...", notes: "...")
# experience = Experience.create!(title: "Get a software engineering job", subtasks: "...", notes: "...")
# experience = Experience.create!(title: "See the northern lights", subtasks: "...", notes: "...")

tag = Tag.create!(name: "Just An Idea")
tag = Tag.create!(name: "Face Your Fears")
tag = Tag.create!(name: "Life Milestones")
tag = Tag.create!(name: "Travel")
tag = Tag.create!(name: "Especially Weird")
tag = Tag.create!(name: "Nothing to It")

# user_experience = UserExperience.create!(user_id: "2", experience_id: "1")
# user_experience = UserExperience.create!(user_id: "2", experience_id: "2")
# user_experience = UserExperience.create!(user_id: "1", experience_id: "3")
# user_experience = UserExperience.create!(user_id: "3", experience_id: "4")
# user_experience = UserExperience.create!(user_id: "1", experience_id: "5")
# user_experience = UserExperience.create!(user_id: "1", experience_id: "6")
# user_experience = UserExperience.create!(user_id: "1", experience_id: "7")
# user_experience = UserExperience.create!(user_id: "3", experience_id: "8")
# user_experience = UserExperience.create!(user_id: "1", experience_id: "9")
# user_experience = UserExperience.create!(user_id: "3", experience_id: "10")

experience_tag = ExperienceTag.create!(experience_id: "1", tag_id: "4")
experience_tag = ExperienceTag.create!(experience_id: "2", tag_id: "4")
experience_tag = ExperienceTag.create!(experience_id: "2", tag_id: "6")
experience_tag = ExperienceTag.create!(experience_id: "3", tag_id: "3")
experience_tag = ExperienceTag.create!(experience_id: "4", tag_id: "5")
experience_tag = ExperienceTag.create!(experience_id: "4", tag_id: "1")
experience_tag = ExperienceTag.create!(experience_id: "5", tag_id: "6")
# experience_tag = ExperienceTag.create!(experience_id: "6", tag_id: "2")
# experience_tag = ExperienceTag.create!(experience_id: "6", tag_id: "3")
# experience_tag = ExperienceTag.create!(experience_id: "7", tag_id: "4")
# experience_tag = ExperienceTag.create!(experience_id: "7", tag_id: "1")
# experience_tag = ExperienceTag.create!(experience_id: "8", tag_id: "4")
# experience_tag = ExperienceTag.create!(experience_id: "8", tag_id: "1")
# experience_tag = ExperienceTag.create!(experience_id: "9", tag_id: "3")
# experience_tag = ExperienceTag.create!(experience_id: "10", tag_id: "4")
# experience_tag = ExperienceTag.create!(experience_id: "10", tag_id: "1")
